[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env.production]
  [env.production.context.environment]
    REPLICATE_API_TOKEN = "r8_bcU6GB32FKv6ftBdxkrKyx43s8eiT7v1nVZid"

